Feat/button
depromeet/10mm-client-web pull request #19
Opened 2023-12-01 16:53 UTC by JUNOSHON

## 🤔 해결하려는 문제가 무엇인가요?
Button 컴포넌트 생성

## 🎉 변경 사항
- 1차 MVP 기능에서 사용할 Button 컴포넌트를 구현했습니다.
### 🙏 여기는 꼭 봐주세요!
- `...props` 과 children을 사용해 확장성 있게 구현해봤습니다.
- `....props` 사용 시 props에 className이 들어와도 스타일이 적용되게 하기 위해 className을 props으로 받아 `<button className={`${className}`}>` 와 같이 사용했습니다.

## 🌄 스크린샷
![image](https://github.com/depromeet/10mm-client-web/assets/67476544/e4f5dcb8-e11b-4eb7-bafe-2509b16e84c5)

## 📚 참고

2023-12-01 23:49 UTC, wade3420 commented on src/components/Button.tsx
> +    <button className={`${className}`} {...props} type="button">
variant, text, size, isBlock (width 100% 인지 아닌지) 등의 버튼의 props들은 나중에 정하는 걸까요?

2023-12-01 23:50 UTC, wade3420 commented on src/styled-system/jsx/flex.d.ts
> +export interface FlexProps extends FlexProperties, DistributiveOmit<HTMLStyledProps<'div'>, keyof FlexProperties > {}
eslint ignore 에 넣어뒀는데  안먹힌 걸까요..? diff가 생겼네요

2023-12-02 04:40 UTC, JUNOSHON commented on src/styled-system/jsx/flex.d.ts
> +export interface FlexProps extends FlexProperties, DistributiveOmit<HTMLStyledProps<'div'>, keyof FlexProperties > {}
왜인지 모르겠는데 저는 styled-system 폴더 전체가 diff가 생겼습니다.
그래서 동민님께서 커밋한 내용대로 올려뒀습니다!

2023-12-02 05:08 UTC, sumi-0011 commented on src/styled-system/jsx/flex.d.ts
> +export interface FlexProps extends FlexProperties, DistributiveOmit<HTMLStyledProps<'div'>, keyof FlexProperties > {}
@wade3420 저도 style-system 폴더 전체에 diff가 생겼는데, eslint ignore에 넣고, styled-system의 경로를 바꿔서 문제가 생긴게 아닐까요?

2023-12-02 05:09 UTC, sumi-0011 commented on src/components/Button.tsx
> +    <button className={`${className}`} {...props} type="button">
> variant, text, size, isBlock (width 100% 인지 아닌지) 등의 버튼의 props들은 나중에 정하는 걸까요?
넵 나중에 정하는 것이 좋을 것 같아요! 
isBlock은 disabled 상태를 의미하는 걸까요?
그리고 text의 경우에는 어떤 의미인지 궁금합니다! 버튼에 들어가는 text를 의미한다면 children이 그 역할을 할 수 있을거라고 생각해요!

2023-12-02 05:13 UTC, sumi-0011 requested changes
Button 컴포넌트만을 보았을 때는 어떻게 style이 입혀지는 건지 모르겠어요!
혹시 Button 컴포넌트를 사용할 때 className으로 css를 넘겨서 제어하는거라면, 
Button 컴포넌트에 variant를 이용해 스타일을 제어하는 방법으로 변경했으면 좋을 것 같아요!

### As is
```
<Button className={css({}} /> 
```

### To be
```
<Button variant='primary' />
```

2023-12-02 05:25 UTC, wade3420 commented on src/styled-system/jsx/flex.d.ts
> +export interface FlexProps extends FlexProperties, DistributiveOmit<HTMLStyledProps<'div'>, keyof FlexProperties > {}
아 그러면 정리하면 제가 git에 넣은 버전은 eslint 가 적용된 버전이였고 eslint ignore 에 넣고 나서 생성된 코드라서 diff가 생기는 것일까요? 이것과 같다면 이번 pr 들만 머지되면 diff가 안생길거 같네요!

2023-12-02 05:27 UTC, wade3420 commented on src/components/Button.tsx
> +    <button className={`${className}`} {...props} type="button">
isBlock 은 cta 버튼 처럼 width 100% 인경우에 사용하는 props라고 생각했어요! 
text 는 버튼에 들어가는 text가 맞습니다!

2023-12-02 05:35 UTC, woobottle commented on src/styled-system/css/css.d.ts
> +  raw: (...styles: Array<SystemStyleObject | undefined | null | false>) => SystemStyleObject
styled-system 폴더 하위 내용 이 커밋에 들어온 이유가 궁금해요!!

2023-12-02 05:44 UTC, JUNOSHON commented
> Button 컴포넌트만을 보았을 때는 어떻게 style이 입혀지는 건지 모르겠어요! 혹시 Button 컴포넌트를 사용할 때 className으로 css를 넘겨서 제어하는거라면, Button 컴포넌트에 variant를 이용해 스타일을 제어하는 방법으로 변경했으면 좋을 것 같아요!
> 
> ### As is
> ```
> <Button className={css({}} /> 
> ```
> 
> ### To be
> ```
> <Button variant='primary' />
> ```

As is 의 방법으로 하려고 했습니다! variant 적용해보겠습니다.

2023-12-02 05:45 UTC, wade3420 commented on src/styled-system/css/css.d.ts
> +  raw: (...styles: Array<SystemStyleObject | undefined | null | false>) => SystemStyleObject
https://github.com/depromeet/10mm-client-web/pull/4 이 pr에서 lint 적용된게 올라감 -> eslint ignore 에 넣음 -> lint 적용되지 않은 코드가 생성됨 로 문제 파악 중 입니다

2023-12-02 07:23 UTC, sumi-0011 approved these changes

2023-12-02 12:28 UTC, closed without merging