:art: Badge 컴포넌트 추가
depromeet/10mm-client-web pull request #196
Opened 2023-12-26 14:10 UTC by woobottle

## 🤔 해결하려는 문제가 무엇인가요?

closed #193

## 🎉 변경 사항
* 디자인 시스템 중 Badge 컴포넌트를 추가하였습니다

### 🙏 여기는 꼭 봐주세요!

### 사용 방법

## 🌄 스크린샷
![image](https://github.com/depromeet/10mm-client-web/assets/50283326/feaf72ab-0e60-4591-9a55-37c9e10c75d6)

## 📚 참고

2023-12-26 15:32 UTC, sumi-0011 requested changes
리뷰 한번 읽어주세요! 👍🏻

2023-12-26 15:32 UTC, sumi-0011 commented on src/components/Badge/Badge.stories.tsx
> +      >
기본적으로 `textStyle`을 주지 않고, 안에서 한 이유가 있을까요? 👀
뱃지의 기본 스타일로 ` textStyle: 'body5',`을 주어도 괜찮을 것 같습니다!

2023-12-26 15:32 UTC, sumi-0011 commented on src/components/Badge/Badge.tsx
> +    padding: '3px 10px 3px 10px',
위에서 ` textStyle: 'body5',`을 밖에서 주도록했는데,
만약 `body5`보다 큰 텍스트를 넣게 된다면 디자인에서 의도한 `height: 23px`을 넘게되어 글자가 삐져나오는 현상이 발생할 것 같습니다. 

밑의 두과정이 추가되어야 디자인팀에서 의도한 뱃지 디자인이 기본적으로 나올것 같아요! 
1. height를 제거한다. 
2. 기본 textStyle을 추가한다.

2023-12-26 15:38 UTC, woobottle commented on src/components/Badge/Badge.tsx
> +    padding: '3px 10px 3px 10px',
2로 갑니도~

2023-12-26 15:39 UTC, woobottle commented on src/components/Badge/Badge.stories.tsx
> +      >
디자인 시스템에서 text를 주지 않아서 일단 위와같이 구현했었어요!
기본 스타일 세팅해 버리죠~

2023-12-27 05:29 UTC, sumi-0011 approved these changes
👍🏻

2023-12-27 05:29 UTC, sumi-0011 commented on src/components/Badge/Badge.tsx
> +    textStyle: 'body5',
리뷰 반영 확인했습니다 👍🏻

2023-12-27 05:47 UTC, merged