[Design] snackBar 컴포넌트 추가
depromeet/10mm-client-web pull request #212
Opened 2023-12-28 08:42 UTC by wade3420

## 🤔 해결하려는 문제가 무엇인가요?
closed #201 

## 🎉 변경 사항
- snackBar 컴포넌트 추가
- useSnackBar 추가
- [formatMMSS 함수 utils 폴더로 변경](https://github.com/depromeet/10mm-client-web/commit/a0ffe44ad6f19da9bdf8c1265eec6edcc99cacb0)

### 🙏 여기는 꼭 봐주세요!
- useSnackBar 를 쓰기위해서 (전역에서 상태 관리해야하기 때문에) contextAPI 를 사용합니다.
- 혹시 다른 전역 상태관리 라이브러리 도입에 의견있으시면 알려주세여

- 

### 사용 방법
useSnackBar 훅을 이용해서 선언적으로 snackbar 를 불러올 수 있습니다.
```ts
  const { triggerSnackBar } = useSnackBar();
  
  const handleClick = () => {
   triggerSnackBar({
       rightAction : 'none',
       message: '메세지'
   })
}

// app bar 가 있는 경우 

  const handleClick = () => {
    triggerSnackBar({
       rightAction : 'none',
       message: '메세지',
       offset : 'appBar'
    })
}
```
자세한것은 스토리북의 withCTA , withAppBar 부분을 참고하시면 됩니다!

## 🌄 스크린샷
<img width="218" alt="스크린샷 2023-12-28 오후 5 41 22" src="https://github.com/depromeet/10mm-client-web/assets/68339352/2632b84d-f838-4831-9fb2-bb7c23294ea4">
<img width="238" alt="스크린샷 2023-12-28 오후 5 41 17" src="https://github.com/depromeet/10mm-client-web/assets/68339352/0c69a20a-8d56-4744-8f85-84e324f12dc0">
<img width="245" alt="스크린샷 2023-12-28 오후 5 41 12" src="https://github.com/depromeet/10mm-client-web/assets/68339352/9e376df2-c0d4-4a72-bbc2-3fba4f543dee">

## 📚 참고

2023-12-28 17:01 UTC, woobottle commented on src/components/SnackBar/SnackBarProvider.tsx
> +    const id = new Date().getTime().toString();
id 추가 및 활용하신 배경이 궁금해요!

2023-12-28 17:01 UTC, woobottle commented on src/components/SnackBar/SnackBarOverlay.tsx
> +        bottom: `80px`,
이 부분이 safaArea 관련 부분이겠군요!

2023-12-28 17:08 UTC, wade3420 commented on src/components/SnackBar/SnackBarProvider.tsx
> +    const id = new Date().getTime().toString();
일정 시간이 지난후에 id를 이용해서 전역상태에 있는 스낵바를 제거 하고 있습니다. 유니크하게 관리되면 좋을 것 같아서 date 객체로 아이디를 생성했습니다

2023-12-29 07:34 UTC, sumi-0011 requested changes
아작리 남겨두었습니당

2023-12-29 07:34 UTC, sumi-0011 commented on src/components/SnackBar/SnackBar.tsx
> +export const snackBarWrapperCss = cva({
`NoneSnackBar`, `IconSnackBar` 등 컴포넌트를 만들때 현재 파일에 있는 `snackBarWrapperCss`을 사용하고 있고, 
현재 파일에서 `NoneSnackBar` 등의 컴포넌트를 import 해서 사용하고 있어 순환참조가 일어나고 있는 것 같아요!

공통적으로 `snackBarWrapperCss` 를 사용하기 위해서라면 따로 `.styles.ts` 파일로 분리하는건 어떨까요

2023-12-29 07:37 UTC, wade3420 commented on src/utils/time.ts
> +export const formatMMSS = (second: number) => {
넵 맞습니다

2023-12-30 13:29 UTC, sumi-0011 approved these changes
리뷰 반영 감사합니다 👍🏻

2023-12-30 13:30 UTC, merged