[Feat] Tab 컴포넌트 구현
depromeet/10mm-client-web pull request #236
Opened 2024-01-01 13:20 UTC by JUNOSHON

## 🤔 해결하려는 문제가 무엇인가요?

closed #220 

## 🎉 변경 사항
-  디자인 시스템의 Tab 컴포넌트를 구현했습니다.

### 🙏 여기는 꼭 봐주세요!
- 디자인 시스템의 명칭과 통일하기 위해 TabParts와 Tab으로 나누어 구현했습니다.
- PR 올린 코드에서 Tab.tsx는 탭바 컴포넌트를 사용하는 예시입니다. 어떤 탭을 클릭하면 해당 탭만 보라색으로 보이고 다른 탭들은 회색으로 보이도록 하기 위해 각 TabParts들을 상위 컴포넌트에서 호출해 status값을 제어할 수 있도록 했습니다.

### 사용 방법
- TabParts를 호출하는 상위 컴포넌트에서 각 TabParts의 status를 제어

## 🌄 스크린샷
![Pasted Graphic](https://github.com/depromeet/10mm-client-web/assets/67476544/7416d8aa-1458-4f99-aba1-8e4d63ec3216)

## 📚 참고

2024-01-01 15:14 UTC, woobottle reviewed
스토리북도 작성 예정인지 궁금해요!

2024-01-01 15:14 UTC, woobottle commented on src/components/Tab/TabParts.tsx
> +  const tabNameCss = css({
이거 컨벤션 관련 같이 이야기 해보고 싶어요~!~!~

2024-01-01 15:14 UTC, woobottle commented on src/components/Tab/Tab.tsx
> +  ]);
탭들을 주입받는 형태로 가게 되는 걸지 궁금합니도~!~!

2024-01-01 15:37 UTC, JUNOSHON commented on src/components/Tab/TabParts.tsx
> +  const tabNameCss = css({
501399fe64 에서 동민형님은 cva로 사용하셨던데, 조건부 스타일링 스레드 파보겠슴니당

2024-01-01 15:47 UTC, JUNOSHON commented on src/components/Tab/Tab.tsx
> +  ]);
탭들을 주입받는다는 말씀을 이해하지 못했습니다 ㅠ_ㅠ TabParts 들의 상태를 Tab에서 제어하려고 했는데, 이 말이 맞을까요??

2024-01-01 16:06 UTC, JUNOSHON commented on src/components/Tab/Tab.tsx
> +  ]);
[3aeb5ec](https://github.com/depromeet/10mm-client-web/pull/236/commits/3aeb5ec38d1d6e953271f218b76399f146b61e33)에서 수정해봤습니다!!

2024-01-02 14:57 UTC, sumi-0011 requested changes
리뷰 한번 확인 부탁드립니당 🙇‍♀️

2024-01-02 14:57 UTC, sumi-0011 commented on src/components/Tab/Tab.stories.tsx
> +import React from 'react';
이부분은 제거해도 괜찮을 것 같습니다!

2024-01-02 14:57 UTC, sumi-0011 commented on src/components/Tab/Tab.tsx
> +  Tabs: Tab[];
변수 이름을 `Tabs`로, 대문자로 한 이유가있을까요?!
type, component 등이 아니므로 `tabs`인 카멜 케이스로 가면 어떨까요!

> 추가적으로 `Tab`이라는 변수를 본다면 컴포넌트라고 생각하게 될 것 같아요. `TabType` 이나 Tab 하나하나의 타입이므로 `TabItemType` 등의 네이밍은 어떨까요? 👀

2024-01-02 14:57 UTC, sumi-0011 commented on src/components/Tab/TabParts.tsx
> +import React, { useEffect, useState } from 'react';
```suggestion
import { useEffect, useState } from 'react';
```

React import는 필요하지 않으니 제거하면 좋을 것 같습니당

2024-01-02 14:57 UTC, sumi-0011 commented on src/components/Tab/TabParts.tsx
> +  status: boolean;
`status`라는 타입을 보았을때 무슨 상태를 나타내는거지? 라는 생각이 들었어요!
active인지 아닌지를 나타내는 변수가 맞다면, `active`또는 `isActive`를 사용하면 조금 더 직관적인 변수명이 아닐까 생각합니다 
> 지극히 개인적인 의견입니다

2024-01-02 14:57 UTC, sumi-0011 commented on src/components/Tab/TabParts.tsx
> +  };
이부분에서 `isActive`라는 상태를 관리하지 않아도 동일한 동작이 이루어질 수 있을것 같아요!

---
만약 stories를 기준으로 `{ tabName: 'Tab 2', active: false },`에 해당하는 tab을 클릭한다고 가정한다면, 

클릭한다면 `TabParts`의 props로 넘겨준 `onTabClick` 메소드가 실행된다면, 
`Tabs` 컴포넌트 내부의 tabs 상태는 아래와 같이 변경될겁니다. 
```tsx
[
      { tabName: 'Tab 1', active: false },
      { tabName: 'Tab 2', active: true },
      { tabName: 'Tab 3', active: false },
]
```

상위 컴포넌트 `Tab`컴포넌트에서 관리하는 `tabs` 상태의 변화가 일어나며 `Tabs`컴포넌트와 하위 컴포넌트의 리렌더링이 일어나고, 
특히 하위 컴포넌트인 `TabParts` 부분을 다시 그리게 될것입니다. 

다시 그리는 `TabParts`의 ` { tabName: 'Tab 2', active: true },` 부분은 `active:true`의 상태로 새로 다시 그려질 것이기 떄문에, 
지금처럼 `TabParts` 컴포넌트 내부에서 `isActive`의 상태관리를 하지 않아도 원하는 동작이 이루어질것 이라고 생각해요. 

---

```
 useEffect(() => {
    //클릭된 탭은 항상 true
    setIsActive(status);
  }, [status]);
```
해당 부분을 추가한 이유를 짐작해보자면 상위 컴포넌트에서 `status`가 바뀌어도 해당 컴포넌트의 status가 변경되지 않아서 props로 넘겨준 `status`가 바뀌면 `isActive` 상태와 동기화를 시켜주기 위해서인것 같아요 🧐

제가 짐작한 이유가 맞다면, 위의 상황이 발생한 것은 해당 컴포넌트 내부에서 useState를 통해 `isActive` 상태관리를 하고 있기 때문입니다!
따라서 `isActive` 상태관리 부분을 제거하고, props로 넘겨주는 `status`를 바로 css에 사용하게 된다면 동일하게 기능이 동작하면서, 상태관리하는 변수가 하나 적어질 수 있을것 같습니다 😚

2024-01-02 14:57 UTC, sumi-0011 commented on src/components/Tab/TabParts.tsx
> +  const tabNameCss = css({
저는 해당 부분에서 동적으로 관리하지 않는 css는 컴포넌트 외부로 빼고, 동적으로 관리하는 css는 inline으로 적어 두 css 조합해서  사용하였습니다! 여러 방식이 있는 것 같아요. 

ex)
```tsx
 <span 
  className={css({tabNameCss, {
     color: isActive ? 'purple.purple700' : 'gray.gray500',
     borderColor: isActive ? 'purple.purple700' : 'bg.surface2',
  })} 
  onClick={handleClick}>
      {tabName}
  </span>
```

2024-01-02 14:57 UTC, sumi-0011 commented on src/hooks/useTabs.tsx
> +interface Tab {
`Tab` 보다는 type이라는 것을 좀더 명확히 보여주기 위해 `TabType`이나 `TabProps` 라는 네이밍을 사용하는 것을 어떤가용?! 🤔

2024-01-02 16:50 UTC, JUNOSHON commented on src/components/Tab/TabParts.tsx
> +import React, { useEffect, useState } from 'react';
제 컴퓨터에서만 그런지 모르겠는데, 이 부분은 import React를 지우면 아래와 같은 경고메시지가 나와서 import React를 냅뒀습니다.
[여기](https://velog.io/@iberis/React%EB%8A%94-UMD-%EC%A0%84%EC%97%AD%EC%9D%84-%EC%B0%B8%EC%A1%B0%ED%95%98%EC%A7%80%EB%A7%8C-%ED%98%84%EC%9E%AC-%ED%8C%8C%EC%9D%BC%EC%9D%80-%EB%AA%A8%EB%93%88%EC%9E%85%EB%8B%88%EB%8B%A4)를 참고했는데 React를 import 하는것으로 해결되어 그대로 냅뒀어요!

![image](https://github.com/depromeet/10mm-client-web/assets/67476544/81ab1f8c-a2eb-479b-8a40-13c55b3fcac8)

2024-01-02 18:45 UTC, JUNOSHON commented on src/components/Tab/Tab.stories.tsx
> +import React from 'react';
800c67c18340ad50fd3d84482262834b54298ab3 에서 수정했어요! 감사합니다.

2024-01-02 18:46 UTC, JUNOSHON commented on src/hooks/useTabs.tsx
> +interface Tab {
a0182a21d5b44c4eda5e51e57dc6cf7bbdecc07b 에서 수정했어요!! 감사합니다 🙌🏻

2024-01-02 18:47 UTC, JUNOSHON commented on src/components/Tab/TabParts.tsx
> +  };
제 생각인데요, 수미님은 천재가 맞는 것 같아요.
3999bf2a1703796949fb0572cb7da043b24769fa 에서 수정했습니다!!

2024-01-02 18:49 UTC, JUNOSHON commented on src/components/Tab/TabParts.tsx
> +  status: boolean;
동민님도 같은 의견이셨어요!! 3999bf2a1703796949fb0572cb7da043b24769fa 여기서 같이 수정했습니다. 디자인 시스템에는 active, inactive 라고 나와있는데 isActive가 더 맞는 표현 같아서 isActive로 수정해두었어요

2024-01-02 18:50 UTC, JUNOSHON commented on src/components/Tab/Tab.tsx
> +  Tabs: Tab[];
변수 이름을 Tabs, 대문자로 한 이유는 useTabs 커스텀 훅에서 tabs 를 사용하고 있어서 그렇게 했습니다!! TabItemType은 수정해두었어요

2024-01-03 02:16 UTC, sumi-0011 commented on src/components/Tab/TabParts.tsx
> +  };
네...? 아닙니당.. 😓

2024-01-03 02:18 UTC, sumi-0011 commented on src/components/Tab/TabParts.tsx
> +  };
[commit](https://github.com/depromeet/10mm-client-web/commit/3999bf2a1703796949fb0572cb7da043b24769fa) 처럼 수정하니
`TabParts`는 view에 좀더 집중하고, 로직은 `Tab`에서 관리할 수 있게된것 같아요! 
리뷰 반영 감사합니다 :D

2024-01-03 02:36 UTC, sumi-0011 commented on src/components/Tab/Tab.tsx
> +  Tabs: Tab[];
`tabs`라는 같은 이름을 사용하는 것이 문제였다면, 생각나는 개선 방법이 두가지가 있는데요! 
> 컴포넌트나 타입이 아닌 변수는 다른곳이랑 일관되게 카멜 케이스를 사용하는 것이 어떤가 싶습니다 🤔
무조건 이 방법으로 변경해달라는 것은 아닙니다! 한번 보고 고려해주시면 좋을 것 같아요 🥺

### 방법 1
> 변수 이름을 바꾼다. 
`tabs`라는 변수를 props로도 받고, custom hook에서 넘겨주는 state로도 받아 이름이 중복된다면, 
하나를 `initialTabs` 라는 네이밍 정도로 바꾸면 해결될 것 같습니다. 

이 방법을 적용한다면, 밑과 같이 변경할 수 있을 것 같아요!
```tsx
interface TabProps {
  tabs: TabItemType[];
}

export default function Tab({ tabs : initialTabs }: TabProps) {
  const { tabs, handleTabClick } = useTabs(initialTabs);
```

### 방법 2
> `tabs` state를 관리하는 방법을 변경한다. 

`tabs` state를 현재는 type에 `tabName`과 `active`가 있는 리스트로 관리하고 있는 상황인데, 
active라는 값까지 리스트로 관리해야할까?🤔 하는 생각이 들었어요. 
active 상태인 tab이 하나가 아니라 여러개라면 (check box list 등의 경우에) active라는 값까지 같이 리스트로 관리한다면 이점이 있을 거라 생각하지만, 
tab의 경우에는 active 상태인 tab이 한 tabs에서 단 하나만 있다고 생각해요. 

그러다 보니 active 상태인 tab이 무엇인지 식별만 가능하면 되지않을까? 하는 생각이 들었고, 
이런 생각의 흐름 끝에 저는 active 상태인 tab의 키(식별 가능한)만을 따로 state로 관리해 사용하는 것 같아요. 

만약 active 상태의 tab key만 state로 관리한다면, 아래와 같은 장점이 있을 것 같습니다. 
- tab을 눌렀을 때마다 리스트를 새로 만들어 state에 저장하지 않고, key 하나만을 새로운 state로 저장할 수 있어요. -> 자그마한 성능 개선이 될 수 있지 않을까 싶습니다 👀
- props로 넘겨준 tabs를 변환하지 않고 그대로 사용할 수 있어요! -> 새로운 tabs state가 필요하지 않기 때문에 이름 중복이 발생하지 않습니다. 
- props로 넘길 `tabs`에는 tabName만이 있어도 원하는 기능을 구현할 수 있어요 (tabName이 unique한 값이라는 가정하에, unique하지 않다면 key가 필요할 것 같습니다)

이방법을 적용한다면 밑과 같은 코드일 것 같아요!
```
export default function Tab({ tabs }: TabProps) {
  const { activeTab, setActiveTab } = useState('초기값');

  const onTabClick = (key) => setActiveTab(key)

  return (
    <div>
      {tabs.map((tab, index) => (
        <TabParts key={index} tabName={tab.tabName} isActive={tab.key === activeTab} onTabClick={onTabClick} />
      ))}
    </div>
  );
}
```

2024-01-03 04:07 UTC, JUNOSHON commented on src/components/Tab/Tab.tsx
> +  Tabs: Tab[];
1e5ca67c87939df0ce29ad5e3c097a50fafeeaeb 에서 **방법 1** 로 수정해뒀습니다.
말씀하신대로 tabs의 state 중 active까지 관리될 필요는 없는 것 같아요 ! 추후 수정해보겠습니다 👏🏻

2024-01-03 06:43 UTC, sumi-0011 approved these changes

2024-01-03 07:10 UTC, merged