[Feat] Input variant normal-button 추가
depromeet/10mm-client-web pull request #266
Opened 2024-01-06 09:05 UTC by JUNOSHON

## 🤔 해결하려는 문제가 무엇인가요?
close #254 

## 🎉 변경 사항
- 01/01 디자인 시스템의 변경된 사항인 Input variant:normal-button 추가
- Input 우측 하단의 글자수의 컬러를 몇 자를 입력하든 text/tertiary 로 통일했습니다.

### 🙏 여기는 꼭 봐주세요!
-  secondary 버튼의 disabled 상태 시 css가 brightness(0.4) 로 되어있어서 0.9로 수정했습니다! 다른 페이지에서 disabled인 small 버튼을 사용하는 곳이 없는 것 같기도 하고, 디자인 팀에서도 disabled 버튼을 컬러 코드가 아닌 퍼센테이지로 관리하는 게 좋겠다고 하셔서 수정해봤어요.
- Input 컴포넌트에 normal-button 케이스를 추가하니까 기존 normal 인풋이 에러가 나네요...TS 에 무지한 저를 도와주시면 감사합니다 😭
![image](https://github.com/depromeet/10mm-client-web/assets/67476544/492296fc-33b4-4a8a-b7a4-ec76e0163507)

### 사용 방법

## 🌄 스크린샷
![image](https://github.com/depromeet/10mm-client-web/assets/67476544/7a6083c0-6540-4547-86c0-02c3222a1744)

## 📚 참고

2024-01-06 09:06 UTC, JUNOSHON commented
normal 인풋 때문에 버셀도 깨진 것 같네요 ㅠ_ㅠ

2024-01-06 15:43 UTC, woobottle commented
<img width="810" alt="image" src="https://github.com/depromeet/10mm-client-web/assets/50283326/6dede5bb-6ae3-4d3b-a2cb-3021e1c208e6">
위 처럼 타입 정의 바꿔주세요~ 
switch 문에서 undefined가 두번째 case문에 걸려있었어서 충돌된것 같아요~


컨플릭 해결해주세요~

2024-01-06 15:47 UTC, woobottle commented on src/components/Input/NormalButtonInput.tsx
> +        {/* 처음엔 안보이다가 input의 길이가 너무 길면 빨간색으로 표시 */}
Todo가 아닌 기능에 대한 주석들은 제거되는게 어떨까 합니다!
기능에 대한 내용은 코드에서 나타내야 한다고 생각해서요

2024-01-06 15:47 UTC, woobottle commented on src/components/Input/NormalButtonInput.tsx
> +          required
required가 아닌 경우에도 required로 동작할 것 같은데 혹시 아닐지 궁금해요!

2024-01-06 15:47 UTC, woobottle commented on src/components/Input/NormalButtonInput.tsx
> +          borderColor: errorMsg ? 'red.red500' : isFocused ? 'purple.purple500' : 'border.default',
삼항연산자의 중복사용은 이해하기가 어려워서 혹시 이 부분 함수 실행되는것으로 변경되면 어떨지 의견이 궁금해요!

2024-01-06 15:47 UTC, woobottle commented on src/components/Input/NormalButtonInput.tsx
> +        <Button
normalInput인데 중복확인이 들어와 있는것 같아서 의견이 궁금해요
모든 normal Input에 중복확인이 default로 들어가게 되는 것일까요?!

2024-01-07 14:40 UTC, sumi-0011 commented on src/components/Input/NormalButtonInput.tsx
> +        {/* 처음엔 안보이다가 input의 길이가 너무 길면 빨간색으로 표시 */}
저도 전체적으로 진짜 필요한 내용이 아니라면 주석은 없는것이 좋다고 생각해요!

2024-01-07 14:41 UTC, sumi-0011 commented on src/components/Input/NormalButtonInput.tsx
> +        <Button
중복 확인은 Normal Input에 해당하지 않는것으로 아는데 다시 한번 확인해보겠습니다! 
제가 알기론 text-?-input 이였던거같아요

2024-01-08 02:59 UTC, JUNOSHON commented on src/components/Input/NormalButtonInput.tsx
> +          required
NormalButtonInput이 쓰이는 플로우에서는 입력이 필수가 되어야 할 것 같아서 required 썼습니다!
이 컴포넌트가 쓰이는곳에서 required가 아닌 경우는 없을 것 같았어요.
required가 제외되어야 할까요??

2024-01-08 03:28 UTC, sumi-0011 commented on src/components/Input/NormalButtonInput.tsx
> +          required
required를 props로 받되, default를 true로 해서 받을 수 있게 하면 어떨까요? 👀

2024-01-08 03:29 UTC, sumi-0011 commented on src/components/Input/NormalButtonInput.tsx
> +          required
축추가적으로 미션 등록 페이지에 `미션 내용`의 경우 required가 아닙니다! 
![image](https://github.com/depromeet/10mm-client-web/assets/49177223/d01b5fdd-8611-45da-b525-143b0f16a5c9)

2024-01-08 14:52 UTC, sumi-0011 requested changes
해당 컴포넌트에 `중복 확인`로직이 들어있는것을 이제 확인했네요 ㅜㅜ 
이부분은 수정하는게 좋을 것 같아요

2024-01-08 14:52 UTC, sumi-0011 commented on src/components/Input/Input.types.ts
> +  positiveMsg?: string;
`positiveMsg` 라는 표현은 몬가몬가 싶어요.  `successMsg`, `validMsg` 등으로 바꾸는건 어떨까요 👀

2024-01-08 14:52 UTC, sumi-0011 commented on src/components/Input/NormalButtonInput.tsx
> +  const [doubleCheckabled, setDoubleCheckAbled] = useState(false);
`doubleCheckabled`를 state로 관리하지 않아도 같은 동작을 수행시킬 수 있을 것 같아요!
`setDoubleCheckAbled` 하는 부분은 삭제해도 될것 같습니다. 
```suggestion
 const doubleCheckabled = inputValue.length === 0;
```

2024-01-08 14:59 UTC, JUNOSHON commented on src/components/Input/Input.types.ts
> +  positiveMsg?: string;
디자인 시스템의 status 네이밍과 통일시키려고 `positiveMsg` 를 사용했어요!
`availableMsg` 는 좀 어색할까요??

2024-01-08 15:39 UTC, JUNOSHON commented on src/components/Input/NormalButtonInput.tsx
> +  const [doubleCheckabled, setDoubleCheckAbled] = useState(false);
disabled 시 brightness 값 확인하려고 넣어 본 상태였는데 제거하지 않았네요 🥲
감사합니다! 6c77b2339698dbcf23d7e2a394a78537af224d2b 에서 제거했습니다.

2024-01-08 15:41 UTC, JUNOSHON commented on src/components/Input/Input.types.ts
> +  positiveMsg?: string;
c43eb8eba63e801f5df6be0d89b7986310206852 에서 수정해봤습니다!!

2024-01-08 15:42 UTC, JUNOSHON commented on src/components/Input/NormalButtonInput.tsx
> +        </Button>
저도 빨리 만들려다가 기본적인걸 빠뜨렸네요 😭
2b1d892dff7de23de254b43b5b1f69dfc82adaa8 에서 수정했어요!!

2024-01-08 15:57 UTC, JUNOSHON commented on src/components/Input/NormalButtonInput.tsx
> +        {/* 처음엔 안보이다가 input의 길이가 너무 길면 빨간색으로 표시 */}
57041c2afeda9ab6f1a97a94b98373969ac2c9ba 에서 수정했습니다!!

2024-01-08 16:06 UTC, wade3420 approved these changes

2024-01-09 03:10 UTC, sumi-0011 approved these changes
수고하셨습니당! 👍🏻

2024-01-09 03:10 UTC, sumi-0011 commented on src/components/Input/NormalButtonInput.tsx
> +          {props.text}
이부분은 `text`라는 네이밍 보다는, 버튼에서만 쓰이는 text이니까 `buttonText` 등으로 좀더 명시해주면 좋을 것 같아요!

2024-01-09 05:08 UTC, merged