[Feat] 미션 등록 페이지 고도화 페이지 구현
depromeet/10mm-client-web pull request #95
Opened 2023-12-19 13:27 UTC by JUNOSHON

## 🤔 해결하려는 문제가 무엇인가요?

- #94 

## 🎉 변경 사항
- SelectMissionForm 컴포넌트의 고도화를 MissionRegistration 컴포넌트에서 진행했습니다.
- Toggle.tsx

### 🙏 여기는 꼭 봐주세요!
- [미션 등록하기](https://www.figma.com/file/waOSgkTYJKQdMHXnGPlOum/%5BDEV%5D-Design-Guide?type=design&node-id=377-2286&mode=design&t=WKinsUdoeJqTklsa-0) 의 디자인 스펙대로 Input에 한글자라도 입력되면 close-circuit 아이콘이 렌더링되도록  구현했습니다.(아직 로직 수정 중)
-  미션명, 미션내용, 카테고리 이 3가지가 모두 Input 컴포넌트로 구현되어야 할까? 하는 의문이 들었습니다. 미션명과 미션내용은 맞는 것 같은데, 카테고리는 성격이 조금 다른 것 같아서요. 
- 카테고리는 선택하는거라 입력이 없고, 나머지는 디자인 스펙대로 입력이 있을 때 아이콘이 렌더링되는데 카테고리 input에 디폴트 값을 넣어둔다던지 등의 이런저런 방법을 시도해보느라 코드가 점점 지저분해지는 것 같아서 PR 남깁니다.

### 사용 방법

## 🌄 스크린샷
![image](https://github.com/depromeet/10mm-client-web/assets/67476544/f3f82e8a-7581-4b55-9300-6627794a7975)

## 📚 참고

2023-12-19 13:47 UTC, sumi-0011 requested changes
리뷰 달은 부분 한번 확인부탁드려용! 😉

2023-12-19 13:47 UTC, sumi-0011 commented on src/app/select/MissionRegistration.tsx
> +        />
디자인을 보았을 때 `카테고리 선택` 같은 경우에는 다른것돠 달리 Input 컴포넌트를 사용하는 것이 아닌. 
바텀 시트 컴포넌트를 사용해야할 것 같습니다! 
`카테고리 선택` 부분을 제외하고 Input 컴포넌트를 구현하면 될 것 같아요

2023-12-19 13:47 UTC, sumi-0011 commented on src/components/Icon/index.tsx
Icon의 type은 SVG의 타입을 확장했으니 svg에서 가능한 props를 모두 받을 수 있을텐데, 그중 `onClick` props도 있을것이라 생각해요! 
그래서 `{...props}` 를 통해서 따로 onClick을 type으로 선언해서 넘겨주지 않아도 될 것 같습니다.

> 뭔소리냐면 위의 코드에서 onClick 부분을 없애도 `<Icon onClick={} />` 이렇게 클릭 이벤트를 줄 수 있을거라는거

2023-12-19 13:47 UTC, sumi-0011 commented on src/components/Input/Input.tsx
>    const [inputValue, setInputValue] = useState(value ? String(value) : '');
`inputValue`로 Input 컴포넌트 내부에서 상태관리가 꼭 필요한걸까요?
`inputValue` 상태를 제거하고, `value` props로 대체해도 동일한 동작이 일어날거라고 예상해요. 

++ 그렇게 되면 `handleChange` 메소드도 필요없어지니 코드가 더 깔끔해지게 될 것 같습니다!

2023-12-19 13:47 UTC, sumi-0011 commented on src/components/Input/Input.tsx
> +        <input className={inputCss} {...inputProps} required autoComplete="off" value={value} onChange={handleChange} />
`{...inputProps}` 이부분이 required 앞에 있어, 
만약 Input 컴포넌트에 `required: false` 옵션을 주더라고 적용되지 않을 것 같아요 😭

2023-12-20 04:05 UTC, JUNOSHON commented on src/components/Icon/index.tsx
이해했습니다! 수정해볼게요

2023-12-21 16:26 UTC, woobottle commented
디자인 qa 내용들 

1. 혹시 카테고리 선택은 빠진것인지 궁금해요!
2. 친구애게 미션공개하기 박스 양옆 여백이 피그마와 다른 것 같은데 확인 요청 드리고 싶어요!
3. 페이지 타이틀이 피그마와 다른것 같아요! 
> 하루 10분씩 2주 동안 어떤 일에 투자하고 싶은가요?
4. 헤더 > 백 버튼 미션등록 쪽에 세로 가운데 정렬이 필요할 것 같아요!

2023-12-22 03:18 UTC, sumi-0011 commented
> 디자인 qa 내용들
> 
> 1. 혹시 카테고리 선택은 빠진것인지 궁금해요!
> 2. 친구애게 미션공개하기 박스 양옆 여백이 피그마와 다른 것 같은데 확인 요청 드리고 싶어요!
> 3. 페이지 타이틀이 피그마와 다른것 같아요!
> 
> > 하루 10분씩 2주 동안 어떤 일에 투자하고 싶은가요?
> 
> 4. 헤더 > 백 버튼 미션등록 쪽에 세로 가운데 정렬이 필요할 것 같아요!

1번의 경우는 제가 맡는다고 한 바텀 시트와 연관이 있어 빠지는 것이 맞습니다!

2023-12-22 12:59 UTC, JUNOSHON commented on src/components/Toggle/Toggle.tsx
> +        {/*
해당 주석을 추가하지 않으면 `A form label must be associated with a control.eslintjsx-a11y/label-has-associated-control ` 린트 에러가 떠서 추가해뒀습니다. ba8b31ead4a6c4b5628206a52e42a8f055e1f904 에서 수정했습니다!

2023-12-22 14:48 UTC, sumi-0011 approved these changes

2023-12-22 14:49 UTC, merged